import AccessDenied from "../Components/AccessDenied";
import Dashboard from "../Views/Dashboard/Dashboard";
import DashboardOverview from "../Views/Dashboard/DashboardOverview";

/**
 * Routes Array
 * Same properties should match for all attributes
 */
const routes = [
  {
    path: "/",
    exact: true,
    component: Dashboard,
    private: true,
  },
  {
    path: "/dashboard",
    exact: true,
    component: Dashboard,
    private: true,
  },
  {
    path: "/dashboard/overview",
    exact: true,
    component: Dashboard,
    private: true,
  },
  //   {
  //     path: "/dashboard/business-overview",
  //     exact: true,
  //     component: DashboardOverview,
  //     private: true,
  //     role: RoleDashboard,
  //   },
  //   {
  //     path: "/reports/inventory-transactions",
  //     exact: true,
  //     component: InventoryTransaction,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/sales-by-product-details",
  //     exact: true,
  //     component: SalesByProductDetails,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/sales-by-items",
  //     exact: true,
  //     component: SalesByItems,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: INVENTORY_MAPPING,
  //     exact: true,
  //     component: InventoryMapping,
  //     private: true,
  //     role: RoleInventory,
  //   },
  //   {
  //     path: "/item",
  //     exact: true,
  //     component: Item,
  //     private: true,
  //     role: RoleInventory,
  //   },
  //   {
  //     path: ITEM_VOID,
  //     exact: true,
  //     component: Item,
  //     private: true,
  //     role: RoleInventory,
  //   },
  //   {
  //     path: "/item/details/:id",
  //     exact: true,
  //     component: ItemDetails,
  //     private: true,
  //     role: RoleInventory,
  //   },
  //   {
  //     path: "/transactions",
  //     exact: true,
  //     component: Transactions,
  //     private: true,
  //     role: RoleInventory,
  //   },
  //   {
  //     path: "/warehouse",
  //     exact: true,
  //     component: WareHouse,
  //     private: true,
  //     role: RoleInventory,
  //   },
  //   {
  //     path: "/workbook",
  //     exact: true,
  //     component: Workbook,
  //     private: true,
  //     role: RoleInventory,
  //   },
  //   {
  //     path: "/workbook/details/:id",
  //     exact: true,
  //     component: WorkbookDetails,
  //     private: true,
  //     role: RoleInventory,
  //   },
  //   {
  //     path: "/product-pricing",
  //     exact: true,
  //     component: ProductPricing,
  //     private: true,
  //     role: RoleInventory,
  //   },
  //   {
  //     path: "/contact/all",
  //     exact: true,
  //     component: AllContact,
  //     private: true,
  //     role: RoleContact,
  //   },
  //   {
  //     path: CONTACT_VOID,
  //     exact: true,
  //     component: AllContact,
  //     private: true,
  //     role: RoleContact,
  //   },
  //   {
  //     path: "/contact/customer",
  //     exact: true,
  //     component: Customer,
  //     private: true,
  //     role: RoleContact,
  //   },
  //   {
  //     path: "/contact/details/:id",
  //     exact: true,
  //     component: ContactsDetails,
  //     private: true,
  //     role: RoleContact,
  //   },
  //   {
  //     path: "/contact/supplier",
  //     exact: true,
  //     component: Supplier,
  //     private: true,
  //     role: RoleContact,
  //   },
  //   {
  //     path: "/contact/salesperson",
  //     exact: true,
  //     component: SalesPerson,
  //     private: true,
  //     role: RoleContact,
  //   },
  //   {
  //     path: "/cashbank",
  //     exact: true,
  //     component: CashAndBank,
  //     private: true,
  //     role: RoleBanking,
  //   },
  //   {
  //     path: "/cashbank/match-transaction/:id",
  //     exact: true,
  //     component: MatchTransactionsPage,
  //     private: true,
  //     role: RoleBanking,
  //   },
  //   {
  //     path: "/cashbank/transaction/details/:id",
  //     exact: true,
  //     component: TransactionDetail,
  //     private: true,
  //     role: RoleBanking,
  //   },
  //   {
  //     path: "/journal-transactions",
  //     exact: true,
  //     component: JournalTransactions,
  //     private: true,
  //     role: RoleBanking,
  //   },
  //   {
  //     path: "/sales",
  //     exact: true,
  //     component: Sales,
  //     private: true,
  //     role: RoleSales,
  //   },
  //   {
  //     path: SALES_VOID,
  //     exact: true,
  //     component: Sales,
  //     private: true,
  //     role: RoleSales,
  //   },
  //   {
  //     path: "/sales/details/:id",
  //     exact: true,
  //     component: ViewInvoice,
  //     private: true,
  //     role: RoleSales,
  //   },
  //   {
  //     path: "/history/:id",
  //     exact: true,
  //     component: ItemHistory,
  //     private: true,
  //   },
  //   {
  //     path: "/challan",
  //     exact: true,
  //     component: Sales,
  //     private: true,
  //     role: RoleSales,
  //   },
  //   {
  //     path: "/challan/details/:id",
  //     exact: true,
  //     component: ViewInvoice,
  //     private: true,
  //     role: RoleSales,
  //   },
  //   {
  //     path: "/purchase",
  //     exact: true,
  //     component: Purchase,
  //     private: true,
  //     role: RolePurchase,
  //   },
  //   {
  //     path: "/purchase/details/:id",
  //     exact: true,
  //     component: ViewPurchaseInvoice,
  //     private: true,
  //     role: RolePurchase,
  //   },
  //   {
  //     path: "/purchase-challan",
  //     exact: true,
  //     component: PurchaseChallan,
  //     private: true,
  //     role: RolePurchase,
  //   },
  //   {
  //     path: "/purchase-challan/details/:id",
  //     exact: true,
  //     component: ViewPurchaseChallan,
  //     private: true,
  //     role: RolePurchase,
  //   },
  //   {
  //     path: "/sales-order",
  //     exact: true,
  //     component: SalesOrder,
  //     private: true,
  //     role: RoleOrders,
  //   },
  //   {
  //     path: "/sales-order/details/:id",
  //     exact: true,
  //     component: SalesOrderDetails,
  //     private: true,
  //     role: RoleOrders,
  //   },
  //   {
  //     path: "/online-orders/:type/products/view",
  //     exact: true,
  //     component: OrderPreview,
  //     private: true,
  //     role: RoleOnlineOrders,
  //   },
  //   {
  //     path: "/online-orders/pickup-list/history",
  //     exact: true,
  //     component: OnlinePickUpListSavedHistory,
  //     private: true,
  //     role: RoleOnlineOrders,
  //   },
  //   {
  //     path: "/offline-orders/:type/products/view",
  //     exact: true,
  //     component: OfflinePickupListPreview,
  //     private: true,
  //     role: RoleOrders,
  //   },

  //   {
  //     path: "/offline-orders",
  //     exact: true,
  //     component: Offline,
  //     private: true,
  //     role: RoleOrders,
  //   },
  //   {
  //     path: "/offline-orders/details/:id",
  //     exact: true,
  //     component: OfflineOrdersDetails,
  //     private: true,
  //     role: RoleOrders,
  //   },
  //   {
  //     path: "/online-orders",
  //     exact: true,
  //     component: Online,
  //     private: true,
  //     role: RoleOnlineOrders,
  //   },
  //   {
  //     path: "/online-orders/new",
  //     exact: true,
  //     component: NewOrderItem,
  //     private: true,
  //     role: RoleOnlineOrders,
  //   },
  //   {
  //     path: "/online-orders/details/:id",
  //     exact: true,
  //     component: OnlineOrdersDetails,
  //     private: true,
  //     role: RoleOnlineOrders,
  //   },
  //   {
  //     path: "/online-orders/:id",
  //     exact: true,
  //     component: NewOrderItem,
  //     private: true,
  //     role: RoleOnlineOrders,
  //   },
  //   {
  //     path: "/creditnotes",
  //     exact: true,
  //     component: CreditNotes,
  //     private: true,
  //     role: RoleSales,
  //   },
  //   {
  //     path: "/creditnotes/details/:id",
  //     exact: true,
  //     component: ViewCreditNotesInvoice,
  //     private: true,
  //     role: RoleSales,
  //   },
  //   {
  //     path: "/debitnotes",
  //     exact: true,
  //     component: DebitNotes,
  //     private: true,
  //     role: RolePurchase,
  //   },
  //   {
  //     path: "/debitnotes/details/:id",
  //     exact: true,
  //     component: ViewDebitNotesInvoice,
  //     private: true,
  //     role: RolePurchase,
  //   },
  //   {
  //     path: "/chats",
  //     exact: true,
  //     component: Chats,
  //     private: true,
  //   },
  //   {
  //     path: "/my-profile",
  //     exact: true,
  //     component: MyProfile,
  //     private: true,
  //   },
  //   {
  //     path: "/org-details",
  //     exact: true,
  //     component: OrganizaionAndProfile,
  //     private: true,
  //   },
  //   {
  //     path: "/users-and-roles",
  //     exact: true,
  //     component: UserAndRoles,
  //     private: true,
  //     role: RoleUserAndRoles,
  //   },
  //   {
  //     path: "/inventory-reasons",
  //     exact: true,
  //     component: InventoryReasons,
  //     private: true,
  //   },
  //   {
  //     path: "/sales-settings",
  //     exact: true,
  //     component: SettingSales,
  //     private: true,
  //   },
  //   {
  //     path: "/chart-of-accounts",
  //     exact: true,
  //     component: ChartofAccounts,
  //     private: true,
  //   },
  //   {
  //     path: "/opening-balance",
  //     exact: true,
  //     component: OpeningBalance,
  //     private: true,
  //   },
  //   {
  //     path: "/email-settings",
  //     exact: true,
  //     component: EmailSetting,
  //     private: true,
  //   },
  //   {
  //     path: "/reports",
  //     exact: true,
  //     component: Reports,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/journals",
  //     exact: true,
  //     component: Journal,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/trial-balance",
  //     exact: true,
  //     component: TrialBalance,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/tds-payable",
  //     exact: true,
  //     component: TDSPayable,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/profit-loss",
  //     exact: true,
  //     component: ProfitAndLoss,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/balance-sheet",
  //     exact: true,
  //     component: BalanceSheet,
  //     private: true,
  //     role: RoleReports,
  //   },

  //   {
  //     path: "/reports/general-ledger",
  //     exact: true,
  //     component: GeneralLedgerSummary,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/general-ledger-details",
  //     exact: true,
  //     component: GeneraLedgerDetails,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/general-expense",
  //     exact: true,
  //     component: GeneralExpense,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/inventory-items",
  //     exact: true,
  //     component: InventoryItemsSummary,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/inventory-item-details",
  //     exact: true,
  //     component: Dashboard,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/cash-bank-summary",
  //     exact: true,
  //     component: CashAndBankSummary,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/cash-bank-details",
  //     exact: true,
  //     component: CashAndBankDetails,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/aged-receivables",
  //     exact: true,
  //     component: OutstandingReceivables,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/aged-receivables-details",
  //     exact: true,
  //     component: OutstandingReceivablesDetails,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/outstanding-invoice-summary",
  //     exact: true,
  //     component: OutstandingInvoiceSummary,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/customer-ledger-summary",
  //     exact: true,
  //     component: CustomerLedgerSummary,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/customer-ledger-details",
  //     exact: true,
  //     component: CustomerLedgerDetails,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/income-by-customer",
  //     exact: true,
  //     component: SalesIncomeByCustomer,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/sales-by-salesperson",
  //     exact: true,
  //     component: SalesBySalesPerson,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/sales-by-salesperson-details",
  //     exact: true,
  //     component: SalesBySalesPersonDetail,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/sales-invoice-summary",
  //     exact: true,
  //     component: SalesInvoiceSummary,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/gst-r1",
  //     exact: true,
  //     component: GSTR1Summary,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/gst-r2",
  //     exact: true,
  //     component: GSTR2Summary,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/gst-r2-verification",
  //     exact: true,
  //     component: GSTR2Verification,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/gst-r3b",
  //     exact: true,
  //     component: GSTR3B,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/purchase-report",
  //     exact: true,
  //     component: PurchaseReport,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/aged-payables",
  //     exact: true,
  //     component: OutstandingPayables,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/aged-payables-details",
  //     exact: true,
  //     component: outstandingPayablesDetails,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/payable-invoice-summary",
  //     exact: true,
  //     component: PayableInvoiceSummary,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/supplier-ledger-summary",
  //     exact: true,
  //     component: SupplierLedgerSummary,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/supplier-ledger-details",
  //     exact: true,
  //     component: SupplierLedgerDetails,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/outcome-by-vendor",
  //     exact: true,
  //     component: OutcomeBySupplier,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/reports/purchase-invoice-summary",
  //     exact: true,
  //     component: PurchaseInvoiceSummary,
  //     private: true,
  //     role: RoleReports,
  //   },
  //   {
  //     path: "/import",
  //     exact: true,
  //     component: Import,
  //     private: true,
  //   },
  //   {
  //     path: "/item/sku-qty-stocks",
  //     exact: true,
  //     component: ImportSkuQtyList,
  //     private: true,
  //   },
  //   {
  //     path: "/catalogue",
  //     exact: true,
  //     component: Catalogue,
  //     private: true,
  //   },
  //   {
  //     path: "/announcement",
  //     exact: true,
  //     component: Announcement,
  //     private: true,
  //   },
  //   {
  //     path: "/view/announcement",
  //     exact: true,
  //     component: AnnouncementList,
  //     private: true,
  //   },
  //   {
  //     path: "/channel",
  //     exact: true,
  //     component: Channel,
  //     private: true,
  //     role: RoleOnlineOrders,
  //   },
  //   {
  //     path: "/courier",
  //     exact: true,
  //     component: Courier,
  //     private: true,
  //     role: RoleOnlineOrders,
  //   },
  //   {
  //     path: "/payment-gatway",
  //     exact: true,
  //     component: PaymentGateway,
  //     private: true,
  //     role: RoleOnlineOrders,
  //   },
  {
    path: "/access-denied",
    exact: true,
    component: AccessDenied,
    private: true,
  },
];
export default routes;
